name: server
services:
  db:
    image: postgres:15.3
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=gitpod
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=example
    volumes:
      - ./postgres:/var/lib/postgresql/data
